### ISSUE TITLE
Issue using docker-compose file

### ISSUE THREAD

**Issue by blubbi321** [ip-tools/ip-navigator#5] opened 2018-11-29 14:25 UTC
Hey there,
thanks for putting together such a nice application!

Trying to get things to run using the docker-compose file I run into the following issue:

```
mongodb     | 2018-11-29T14:15:13.521+0000 I NETWORK  [listener] connection accepted from 172.20.0.1:40760 #1 (1 connection now open)
patzilla    | Starting server in PID 1.
patzilla    | 2018-11-29 14:15:30,952 INFO     [patzilla.access.epo.ops.client          ][waitress] OpsOAuthClientFactory.create_session: identifier=system, client_id=4DhorgG67fAWrGxRkJr2hFqJAdS7bs7b
patzilla    | 2018-11-29 14:15:30,992 ERROR    [waitress                                ][waitress] Exception when serving /navigator/
patzilla    | Traceback (most recent call last):
patzilla    |   File "/usr/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
patzilla    |     task.service()
patzilla    |   File "/usr/lib/python2.7/site-packages/waitress/task.py", line 169, in service
patzilla    |     self.execute()
patzilla    |   File "/usr/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
patzilla    |     app_iter = self.channel.server.application(env, start_response)
patzilla    |   File "/usr/lib/python2.7/site-packages/paste/deploy/config.py", line 291, in __call__
patzilla    |     return self.app(environ, start_response)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
patzilla    |     response = self.execution_policy(environ, self)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 278, in default_execution_policy
patzilla    |     return request.invoke_exception_view(reraise=True)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 748, in invoke_exception_view
patzilla    |     reraise_(*exc_info)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 276, in default_execution_policy
patzilla    |     return router.invoke_request(request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
patzilla    |     response = handle_request(request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
patzilla    |     response = _error_handler(request, exc)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 12, in _error_handler
patzilla    |     response = request.invoke_exception_view(exc_info)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 744, in invoke_exception_view
patzilla    |     request_iface=request_iface.combined,
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
patzilla    |     response = view_callable(context, request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
patzilla    |     result = view(context, request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
patzilla    |     response = handler(request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
patzilla    |     view_name
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
patzilla    |     response = view_callable(context, request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
patzilla    |     return view(context, request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 462, in rendered_view
patzilla    |     request, result, view_inst, context)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/renderers.py", line 435, in render_view
patzilla    |     return self.render_to_response(response, system, request=request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/renderers.py", line 458, in render_to_response
patzilla    |     result = self.render(value, system_values, request=request)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid/renderers.py", line 454, in render
patzilla    |     result = renderer(value, system_values)
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 156, in __call__
patzilla    |     reraise(MakoRenderingException(errtext), None, exc_info[2])
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
patzilla    |     result = template.render_unicode(**system)
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
patzilla    |     as_unicode=True)
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
patzilla    |     **_kwargs_for_callable(callable_, data))
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
patzilla    |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
patzilla    |     callable_(context, *args, **kwargs)
patzilla    |   File "patzilla_navigator_templates_site_mako", line 52, in render_body
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 748, in _include_file
patzilla    |     template = _lookup_template(context, uri, calling_uri)
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 804, in _lookup_template
patzilla    |     raise exceptions.TemplateLookupException(str(compat.exception_as()))
patzilla    | MakoRenderingException: 
patzilla    | 
patzilla    | Traceback (most recent call last):
patzilla    |   File "/usr/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
patzilla    |     result = template.render_unicode(**system)
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/template.py", line 471, in render_unicode
patzilla    |     as_unicode=True)
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
patzilla    |     **_kwargs_for_callable(callable_, data))
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
patzilla    |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
patzilla    |     callable_(context, *args, **kwargs)
patzilla    |   File "/usr/lib/python2.7/site-packages/patzilla/navigator/templates/site.mako", line 29, in render_body
patzilla    |     <%include file="urlcleaner.js"/>
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 748, in _include_file
patzilla    |     template = _lookup_template(context, uri, calling_uri)
patzilla    |   File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 804, in _lookup_template
patzilla    |     raise exceptions.TemplateLookupException(str(compat.exception_as()))
patzilla    | TemplateLookupException: Can not locate template for uri 'patzilla.navigator:templates/urlcleaner.js'
patzilla    | 
```

I understand that the docker-compose means of installation is probably not supported yet, just wanted to point out the issue. (Also had to add a couple of things to the docker files to get things to work, happy to make a pull request when desired)

**Comment by amotl** [comment] 2018-11-29 15:06
Hi there,

thanks for writing in.

### Intro
> thanks for putting together such a nice application!

Thanks for the kind words, we are always happy to welcome new people interested in this and we are just getting started. The project will be happy to receive stars on GitHub ;].

> I understand that the docker-compose means of installation is probably not supported yet, just wanted to point out the issue.

@aghster put that together the other day. To be honest i haven't actually used it yet as i usually run PatZilla in development mode. Nevertheless, i was very happy about his contribution and will be glad if we can resolve this issue together.

> Also had to add a couple of things to the docker files to get things to work, happy to make a pull request when desired.

Looking forward! Did you even manage to get Open Office inside? Through [unoconv](https://github.com/dagwieers/unoconv), it is used to do some rendering for specific export artefacts.

### The issue itself
It looks like Pyramid is pretty clear on what happened: `TemplateLookupException: Can not locate template for uri` probably means what it says: The application can not access the template in question. So, it is probably some packaging / search path issue.

Maybe @aghster knows something about this error? If not, i will be happy to investigate further.

With kind regards,
Andreas.

**Comment by aghster** [comment] 2018-11-30 08:05
Hi, I just reviewed the docker files and made some modifications, cf. pull request [#6](https://github.com/ip-tools/ip-navigator/pull/6).

I have identified two possible causes for an error. First, a dependency was missing. Second, for patzilla to run properly when executing "docker-compose up -d", a configuration file named patzilla.ini had to be present in the folder, where docker-compose.yml is run from. 

The dependency is now fixed and a default patzilla.ini is now provided. So I would expect that executing "docker-compose up -d" within the docker/ folder should start up a patzilla container out-of-the-box. However, one should still customize patzilla.ini (in particular, at least to include custom api keys) before running the container. 

I do not know whether the errors @blubbi321 encountered are caused by any of these two issues that I have adressed by my amendments, since the error message provided by @blubbi321 prima facie does not seem related to docker. Therefore, I also do not know whether these errors are now fixed by the amendments. But when I now clone the repository, change into the docker/ folder and execute "docker-compose up -d" I can access a running patzilla instance through "127.0.0.1:9999/navigator" in my browser.

**Comment by blubbi321** [comment] 2018-11-30 09:08
@aghster thanks for your quick reply. I had done a bunch of your modifications already, but apparently not enough.

Just tried to clone your repo's "docker-mods" branch and if I run the containers as suggested I get a 
```
404 Not Found
The resource could not be found.

/navigator
```
from http://127.0.0.1:9999/navigator

**Comment by aghster** [comment] 2018-11-30 09:15
This could be due to a missing trailing slash. Please try:

http://127.0.0.1:9999/navigator/

**Comment by aghster** [comment] 2018-11-30 09:53
Sorry for the missing slash. 

I do not think that OO is included, when patzilla is installed from pypi using pip, as is the case in the docker image. Also, I do not think that OO is actually required, since according to @amotl it just serves to do "some rendering for specific export artefacts". To my understanding @amotl simply suggested (or hoped for) that unoconv be included into the image to extend patzilla's functionality. Unfortunately, there seems to be no pre-built unoconv package for alpine (cf. [https://pkgs.alpinelinux.org/packages?name=unoconv&branch=edge](https://pkgs.alpinelinux.org/packages?name=unoconv&branch=edge)). Therefore, one would have to install unoconv and include the required LibreOffice or OpenOffice libraries manually.

**Comment by amotl** [comment] 2018-11-30 10:00
When installing the _patzilla_ package in the process of `docker-compose up`, it will croak when trying to install the _pillow_ package:
```
The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.
```

**Comment by aghster** [comment] 2018-11-30 10:03
That was with the old Dockerfile. With the new one this error should be fixed, since jpeg-dev is now included in the packages that are installed in the image. Is it not? Can you check that your Dockerfile includes jpeg-dev?

**Comment by amotl** [comment] 2018-11-30 10:04
Ah, just have been reading the comments as well as #6:
> I fixed a missing dependency (jpeg-dev, apparently required by pillow) and added some optional libraries (freetype-dev, lcms2-dev, tiff-dev) that I considered possibly useful.

Thank you so much, guys!

**Closed** 2018-11-30 13:22 UTC

**Comment by amotl** [comment] 2018-11-30 14:50
@aghster said:
> This could be due to a missing trailing slash. Please try:

http://127.0.0.1:9999/navigator/

@blubbi321 said:
> omg, then I probably had the thing running a couple of times already :D

I am so sorry about this little detail which I believe is frustrating when getting started. Note to self: Will have to address it more appropriately, at least in the documentation.
